### PR TITLE
Handle non-TTY fallback for watch mode

### LINKED ISSUE #122: `run restart --watch` fails in non-TTY sessions after successfully queuing restart
## CLI Version
teamcity version 0.7.0

## TeamCity Server Version
Not explicitly checked (server: https://teamcity-nightly.labs.intellij.net)

## Operating System
macOS (Darwin)

## What happened?
When running `teamcity run restart <run-id> --watch` from a non-interactive session (no TTY, e.g. AI agent execution), the command successfully queues the restarted build and prints the new run ID, but then exits with code 1 and a TTY error.

Observed output:
```shell
✓ Queued run 5189666 (restart of 5189660)
  Job: Sandbox_Ugdyzhekov_AplDemoPipeline_PackageIt
  URL: https://teamcity-nightly.labs.intellij.net/build/5189666

Usage:
  teamcity run restart <run-id> [flags]
...
Error: could not open a new TTY: open /dev/tty: device not configured
```

This breaks automation flow because the restart itself succeeds, but the command is reported as failed.

## Expected behavior
`teamcity run restart --watch` should work in non-TTY mode, similar to `teamcity run watch <id>`, or degrade gracefully without failing after a successful restart.

At minimum, if watch cannot be attached, the command should not print usage and fail with exit code 1 after already completing the restart action.

## Steps to reproduce
1. Run in a non-TTY shell/session.
2. Execute: `teamcity run restart 5189660 --watch`
3. Observe: new run is queued, then command exits with usage + `could not open a new TTY` error.

## Relevant log output
```shell
✓ Queued run 5189666 (restart of 5189660)
  Job: Sandbox_Ugdyzhekov_AplDemoPipeline_PackageIt
  URL: https://teamcity-nightly.labs.intellij.net/build/5189666

Usage:
  teamcity run restart <run-id> [flags]

Examples:
  teamcity run restart 12345
  teamcity run restart 12345 --watch

Flags:
  -h, --help    help for restart
      --watch   Watch the new run after restarting
  -w, --web     Open run in browser

Global Flags:
      --no-color   Disable colored output
      --no-input   Disable interactive prompts
  -q, --quiet      Suppress non-essential output
      --verbose    Show detailed output including debug info

Error: could not open a new TTY: open /dev/tty: device not configured
```

## Additional note
In the same non-TTY session, `teamcity run watch 5189666` succeeds, so the limitation appears specific to the `restart --watch` path.

### PR DESCRIPTION
**Pull request by sugdyzhekov**
## Summary
- add TTY detection guard before entering Bubble Tea watch UI
- fall back to standard polling watch mode when --logs is used without a TTY
- add unit tests for both fallback and TTY paths

## Testing
- go test ./internal/cmd -run 'TestDoRunWatchLogs'
- go test ./internal/cmd

Closes #122

### CODE REVIEW

File: internal/cmd/run_lifecycle_watch_test.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+	"errors"
+	"net/http"
+	"net/http/httptest"
+	"testing"
+
+	"github.com/JetBrains/teamcity-cli/api"
+)
+
+func TestDoRunWatchLogsFallsBackWithoutTTY(t *testing.T) {
+	t.Helper()
```
Comment (tiulpin) [inline internal/cmd/run_lifecycle_watch_test.go]: t.Helper() call here is not needed since it's already a real test?

File: internal/cmd/run_lifecycle_watch_test.go [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+	if buildRequests < 2 {
+		t.Fatalf("expected at least 2 build requests, got %d", buildRequests)
+	}
+	if logRequests != 0 {
+		t.Fatalf("expected 0 build log requests in fallback mode, got %d", logRequests)
+	}
+}
+
+func TestDoRunWatchLogsUsesTUIWhenTTYIsAvailable(t *testing.T) {
+	t.Helper()
```
Comment (tiulpin) [inline internal/cmd/run_lifecycle_watch_test.go]: t.Helper() call here is not needed since it's already a real test?
